// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/actions/actions-runner-controller/github/actions"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPublisher creates a new instance of MockPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPublisher {
	mock := &MockPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPublisher is an autogenerated mock type for the Publisher type
type MockPublisher struct {
	mock.Mock
}

type MockPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPublisher) EXPECT() *MockPublisher_Expecter {
	return &MockPublisher_Expecter{mock: &_m.Mock}
}

// PublishDesiredRunners provides a mock function for the type MockPublisher
func (_mock *MockPublisher) PublishDesiredRunners(count int) {
	_mock.Called(count)
	return
}

// MockPublisher_PublishDesiredRunners_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishDesiredRunners'
type MockPublisher_PublishDesiredRunners_Call struct {
	*mock.Call
}

// PublishDesiredRunners is a helper method to define mock.On call
//   - count int
func (_e *MockPublisher_Expecter) PublishDesiredRunners(count interface{}) *MockPublisher_PublishDesiredRunners_Call {
	return &MockPublisher_PublishDesiredRunners_Call{Call: _e.mock.On("PublishDesiredRunners", count)}
}

func (_c *MockPublisher_PublishDesiredRunners_Call) Run(run func(count int)) *MockPublisher_PublishDesiredRunners_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPublisher_PublishDesiredRunners_Call) Return() *MockPublisher_PublishDesiredRunners_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPublisher_PublishDesiredRunners_Call) RunAndReturn(run func(count int)) *MockPublisher_PublishDesiredRunners_Call {
	_c.Run(run)
	return _c
}

// PublishJobCompleted provides a mock function for the type MockPublisher
func (_mock *MockPublisher) PublishJobCompleted(msg *actions.JobCompleted) {
	_mock.Called(msg)
	return
}

// MockPublisher_PublishJobCompleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishJobCompleted'
type MockPublisher_PublishJobCompleted_Call struct {
	*mock.Call
}

// PublishJobCompleted is a helper method to define mock.On call
//   - msg *actions.JobCompleted
func (_e *MockPublisher_Expecter) PublishJobCompleted(msg interface{}) *MockPublisher_PublishJobCompleted_Call {
	return &MockPublisher_PublishJobCompleted_Call{Call: _e.mock.On("PublishJobCompleted", msg)}
}

func (_c *MockPublisher_PublishJobCompleted_Call) Run(run func(msg *actions.JobCompleted)) *MockPublisher_PublishJobCompleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *actions.JobCompleted
		if args[0] != nil {
			arg0 = args[0].(*actions.JobCompleted)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPublisher_PublishJobCompleted_Call) Return() *MockPublisher_PublishJobCompleted_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPublisher_PublishJobCompleted_Call) RunAndReturn(run func(msg *actions.JobCompleted)) *MockPublisher_PublishJobCompleted_Call {
	_c.Run(run)
	return _c
}

// PublishJobStarted provides a mock function for the type MockPublisher
func (_mock *MockPublisher) PublishJobStarted(msg *actions.JobStarted) {
	_mock.Called(msg)
	return
}

// MockPublisher_PublishJobStarted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishJobStarted'
type MockPublisher_PublishJobStarted_Call struct {
	*mock.Call
}

// PublishJobStarted is a helper method to define mock.On call
//   - msg *actions.JobStarted
func (_e *MockPublisher_Expecter) PublishJobStarted(msg interface{}) *MockPublisher_PublishJobStarted_Call {
	return &MockPublisher_PublishJobStarted_Call{Call: _e.mock.On("PublishJobStarted", msg)}
}

func (_c *MockPublisher_PublishJobStarted_Call) Run(run func(msg *actions.JobStarted)) *MockPublisher_PublishJobStarted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *actions.JobStarted
		if args[0] != nil {
			arg0 = args[0].(*actions.JobStarted)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPublisher_PublishJobStarted_Call) Return() *MockPublisher_PublishJobStarted_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPublisher_PublishJobStarted_Call) RunAndReturn(run func(msg *actions.JobStarted)) *MockPublisher_PublishJobStarted_Call {
	_c.Run(run)
	return _c
}

// PublishStatic provides a mock function for the type MockPublisher
func (_mock *MockPublisher) PublishStatic(min int, max int) {
	_mock.Called(min, max)
	return
}

// MockPublisher_PublishStatic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishStatic'
type MockPublisher_PublishStatic_Call struct {
	*mock.Call
}

// PublishStatic is a helper method to define mock.On call
//   - min int
//   - max int
func (_e *MockPublisher_Expecter) PublishStatic(min interface{}, max interface{}) *MockPublisher_PublishStatic_Call {
	return &MockPublisher_PublishStatic_Call{Call: _e.mock.On("PublishStatic", min, max)}
}

func (_c *MockPublisher_PublishStatic_Call) Run(run func(min int, max int)) *MockPublisher_PublishStatic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPublisher_PublishStatic_Call) Return() *MockPublisher_PublishStatic_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPublisher_PublishStatic_Call) RunAndReturn(run func(min int, max int)) *MockPublisher_PublishStatic_Call {
	_c.Run(run)
	return _c
}

// PublishStatistics provides a mock function for the type MockPublisher
func (_mock *MockPublisher) PublishStatistics(stats *actions.RunnerScaleSetStatistic) {
	_mock.Called(stats)
	return
}

// MockPublisher_PublishStatistics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishStatistics'
type MockPublisher_PublishStatistics_Call struct {
	*mock.Call
}

// PublishStatistics is a helper method to define mock.On call
//   - stats *actions.RunnerScaleSetStatistic
func (_e *MockPublisher_Expecter) PublishStatistics(stats interface{}) *MockPublisher_PublishStatistics_Call {
	return &MockPublisher_PublishStatistics_Call{Call: _e.mock.On("PublishStatistics", stats)}
}

func (_c *MockPublisher_PublishStatistics_Call) Run(run func(stats *actions.RunnerScaleSetStatistic)) *MockPublisher_PublishStatistics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *actions.RunnerScaleSetStatistic
		if args[0] != nil {
			arg0 = args[0].(*actions.RunnerScaleSetStatistic)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPublisher_PublishStatistics_Call) Return() *MockPublisher_PublishStatistics_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPublisher_PublishStatistics_Call) RunAndReturn(run func(stats *actions.RunnerScaleSetStatistic)) *MockPublisher_PublishStatistics_Call {
	_c.Run(run)
	return _c
}
