// Code generated by mockery v2.36.1. DO NOT EDIT.

package mocks

import (
	context "context"

	actions "github.com/actions/actions-runner-controller/github/actions"
	"go.opentelemetry.io/otel"

	mock "github.com/stretchr/testify/mock"
)

// ServerPublisher is an autogenerated mock type for the ServerPublisher type
type ServerPublisher struct {
	mock.Mock
}

// ListenAndServe provides a mock function with given fields: ctx
func (_m *ServerPublisher) ListenAndServe(ctx context.Context) error {
	ctx, span := otel.Tracer("arc").Start(ctx, "ServerPublisher.ListenAndServe")
	defer span.End()

	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PublishDesiredRunners provides a mock function with given fields: count
func (_m *ServerPublisher) PublishDesiredRunners(count int) {
	_m.Called(count)
}

// PublishJobCompleted provides a mock function with given fields: msg
func (_m *ServerPublisher) PublishJobCompleted(msg *actions.JobCompleted) {
	_m.Called(msg)
}

// PublishJobStarted provides a mock function with given fields: msg
func (_m *ServerPublisher) PublishJobStarted(msg *actions.JobStarted) {
	_m.Called(msg)
}

// PublishStatic provides a mock function with given fields: min, max
func (_m *ServerPublisher) PublishStatic(min int, max int) {
	_m.Called(min, max)
}

// PublishStatistics provides a mock function with given fields: stats
func (_m *ServerPublisher) PublishStatistics(stats *actions.RunnerScaleSetStatistic) {
	_m.Called(stats)
}

// NewServerPublisher creates a new instance of ServerPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServerPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServerPublisher {
	mock := &ServerPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
