run:
  timeout: 5m
output:
  formats:
    - format: colored-line-number
      path: stdout
linters-settings:
  errcheck:
    exclude-functions:
      - (net/http.ResponseWriter).Write
      - (*net/http.Server).Shutdown
      - (*github.com/actions/actions-runner-controller/simulator.VisibleRunnerGroups).Add
      - (*github.com/actions/actions-runner-controller/testing.Kind).Stop
issues:
  exclude-rules:
    - path: controllers/suite_test.go
      linters:
        - staticcheck
      text: "SA1019"
