run:
  timeout: 3m
output:
  format: github-actions
linters-settings:
  errcheck:
    exclude-functions:
      - (net/http.ResponseWriter).Write
      - (*net/http.Server).Shutdown
      - (*github.com/actions-runner-controller/actions-runner-controller/simulator.VisibleRunnerGroups).Add
      - (*github.com/actions-runner-controller/actions-runner-controller/testing.Kind).Stop
issues:
  exclude-rules:
    - path: controllers/suite_test.go
      linters:
        - staticcheck
      text: "SA1019"
