version: "2"
run:
  timeout: 5m
linters:
  settings:
    errcheck:
      exclude-functions:
        - (net/http.ResponseWriter).Write
        - (*net/http.Server).Shutdown
        - (*github.com/actions/actions-runner-controller/simulator.VisibleRunnerGroups).Add
        - (*github.com/actions/actions-runner-controller/testing.Kind).Stop
  exclusions:
    presets:
      - std-error-handling
