packages:
  github.com/actions/actions-runner-controller/github/actions:
    interfaces:
      ActionsService:
        config:
          inpackage: true
      SessionService:
        config:
          inpackage: true

  github.com/actions/actions-runner-controller/cmd/ghalistener/metrics:
    config:
      dir: "{{.InterfaceDir}}/mocks"
      pkgname: mocks
      filename: "{{.InterfaceName|snakecase}}.go"
    interfaces:
      Publisher:
      ServerExporter:
        config:
          structname: ServerPublisher
          filename: server_publisher.go

  github.com/actions/actions-runner-controller/cmd/ghalistener/app:
    config:
      dir: "{{.InterfaceDir}}/mocks"
      pkgname: mocks
      filename: "{{.InterfaceName|snakecase}}.go"
    interfaces:
      Listener:
      Worker:
