all: false
dir: "{{.InterfaceDir}}"
filename: mocks_test.go
force-file-write: true
formatter: goimports
log-level: info
structname: "{{.Mock}}{{.InterfaceName}}"
pkgname: "{{.SrcPackageName}}"
recursive: false
template: testify
packages:
  github.com/actions/actions-runner-controller/cmd/ghalistener/metrics:
    config:
      all: true
  github.com/actions/actions-runner-controller/controllers/actions.github.com:
    config:
      all: true
