# TODO(cory-miller): Setup multistage with alpine.
# For now the dev tools are useful for prototyping.
FROM golang:1.18
WORKDIR $GOPATH/autoscaler/
COPY . .
RUN go mod download
RUN go mod verify
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -ldflags="-w -s" -a \
    -o /bin/autoscaler ./cmd/githubrunnerscalesetlistener/
ENTRYPOINT ["/bin/autoscaler"]
