resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: summerwind/actions-runner-controller
  newTag: latest

replacements:
- path: env-replacement.yaml
