// Code generated by mockery v2.36.1. DO NOT EDIT.

package mocks

import (
	context "context"

	listener "github.com/actions/actions-runner-controller/cmd/ghalistener/listener"
	mock "github.com/stretchr/testify/mock"
	"go.opentelemetry.io/otel"
)

// Listener is an autogenerated mock type for the Listener type
type Listener struct {
	mock.Mock
}

// Listen provides a mock function with given fields: ctx, handler
func (_m *Listener) Listen(ctx context.Context, handler listener.Handler) error {
	ctx, span := otel.Tracer("arc").Start(ctx, "Listener.Listen")
	defer span.End()

	ret := _m.Called(ctx, handler)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, listener.Handler) error); ok {
		r0 = rf(ctx, handler)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewListener creates a new instance of Listener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewListener(t interface {
	mock.TestingT
	Cleanup(func())
}) *Listener {
	mock := &Listener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
