// Code generated by mockery v2.36.1. DO NOT EDIT.

package mocks

import (
	actions "github.com/actions/actions-runner-controller/github/actions"

	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Worker is an autogenerated mock type for the Worker type
type Worker struct {
	mock.Mock
}

// HandleDesiredRunnerCount provides a mock function with given fields: ctx, desiredRunnerCount
func (_m *Worker) HandleDesiredRunnerCount(ctx context.Context, desiredRunnerCount int) error {
	ret := _m.Called(ctx, desiredRunnerCount)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, desiredRunnerCount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HandleJobStarted provides a mock function with given fields: ctx, jobInfo
func (_m *Worker) HandleJobStarted(ctx context.Context, jobInfo *actions.JobStarted) error {
	ret := _m.Called(ctx, jobInfo)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *actions.JobStarted) error); ok {
		r0 = rf(ctx, jobInfo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewWorker creates a new instance of Worker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWorker(t interface {
	mock.TestingT
	Cleanup(func())
}) *Worker {
	mock := &Worker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
