# permissions for end users to edit autoscalinglisteners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: autoscalinglistener-editor-role
rules:
- apiGroups:
  - actions.github.com
  resources:
  - autoscalinglisteners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - actions.github.com
  resources:
  - autoscalinglisteners/status
  verbs:
  - get
