# permissions for end users to view ephemeralrunnersets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ephemeralrunnerset-viewer-role
rules:
- apiGroups:
  - actions.github.com
  resources:
  - ephemeralrunnersets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - actions.github.com
  resources:
  - ephemeralrunnersets/status
  verbs:
  - get
