# permissions for end users to edit ephemeralrunners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ephemeralrunner-editor-role
rules:
- apiGroups:
  - actions.github.com
  resources:
  - ephemeralrunners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - actions.github.com
  resources:
  - ephemeralrunners/status
  verbs:
  - get
