{{- if .Values.actionsMetricsServer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "actions-runner-controller-actions-metrics-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "actions-runner-controller.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.actionsMetricsServer.replicaCount }}
  selector:
    matchLabels:
      {{- include "actions-runner-controller-actions-metrics-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.actionsMetricsServer.podAnnotations }}
      annotations:
        kubectl.kubernetes.io/default-container: "actions-metrics-server"
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "actions-runner-controller-actions-metrics-server.selectorLabels" . | nindent 8 }}
      {{- with .Values.actionsMetricsServer.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.actionsMetricsServer.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "actions-runner-controller-actions-metrics-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.actionsMetricsServer.podSecurityContext | nindent 8 }}
      {{- with .Values.actionsMetricsServer.priorityClassName }}
      priorityClassName: "{{ . }}"
      {{- end }}
      containers:
      - args:
        {{- $metricsHost := .Values.actionsMetrics.proxy.enabled | ternary "127.0.0.1" "0.0.0.0" }}
        {{- $metricsPort := .Values.actionsMetrics.proxy.enabled | ternary "8080" .Values.actionsMetrics.port }}
        - "--metrics-addr={{ $metricsHost }}:{{ $metricsPort }}"
        {{- if .Values.actionsMetricsServer.logLevel }}
        - "--log-level={{ .Values.actionsMetricsServer.logLevel }}"
        {{- end }}
        {{- if .Values.runnerGithubURL  }}
        - "--runner-github-url={{ .Values.runnerGithubURL }}"
        {{- end }}
        {{- if .Values.actionsMetricsServer.logFormat  }}
        - "--log-format={{ .Values.actionsMetricsServer.logFormat }}"
        {{- end }}
        command:
        - "/actions-metrics-server"
        {{- if .Values.actionsMetricsServer.lifecycle }}
        {{- with .Values.actionsMetricsServer.lifecycle }}
        lifecycle:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- end }}
        env:
        - name: GITHUB_WEBHOOK_SECRET_TOKEN
          valueFrom:
            secretKeyRef:
              key: github_webhook_secret_token
              name: {{ include "actions-runner-controller-actions-metrics-server.secretName" . }}
              optional: true
        {{- if .Values.githubEnterpriseServerURL  }}
        - name: GITHUB_ENTERPRISE_URL
          value: {{ .Values.githubEnterpriseServerURL }}
        {{- end }}
        {{- if .Values.githubURL  }}
        - name: GITHUB_URL
          value: {{ .Values.githubURL }}
        {{- end }}
        {{- if .Values.githubUploadURL  }}
        - name: GITHUB_UPLOAD_URL
          value: {{ .Values.githubUploadURL }}
        {{- end }}
        {{- if .Values.actionsMetricsServer.secret.enabled }}
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              key: github_token
              name: {{ include "actions-runner-controller-actions-metrics-server.secretName" . }}
              optional: true
        - name: GITHUB_APP_ID
          valueFrom:
            secretKeyRef:
              key: github_app_id
              name: {{ include "actions-runner-controller-actions-metrics-server.secretName" . }}
              optional: true
        - name: GITHUB_APP_INSTALLATION_ID
          valueFrom:
            secretKeyRef:
              key: github_app_installation_id
              name: {{ include "actions-runner-controller-actions-metrics-server.secretName" . }}
              optional: true
        - name: GITHUB_APP_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              key: github_app_private_key
              name: {{ include "actions-runner-controller-actions-metrics-server.secretName" . }}
              optional: true
        {{- if .Values.authSecret.github_basicauth_username }}
        - name: GITHUB_BASICAUTH_USERNAME
          value: {{ .Values.authSecret.github_basicauth_username }}
        {{- end }}
        - name: GITHUB_BASICAUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              key: github_basicauth_password
              name: {{ include "actions-runner-controller.secretName" . }}
              optional: true
        {{- end }}
        {{- if kindIs "slice" .Values.actionsMetricsServer.env }}
        {{- toYaml .Values.actionsMetricsServer.env | nindent 8 }}
        {{- else }}
        {{- range $key, $val := .Values.actionsMetricsServer.env }}
        - name: {{ $key }}
          value: {{ $val | quote }}
        {{- end }}
        {{- end }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag  | default (cat "v" .Chart.AppVersion | replace " " "") }}"
        name: actions-metrics-server
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        {{- if not .Values.actionsMetrics.proxy.enabled }}
        - containerPort: {{ .Values.actionsMetrics.port }}
          name: metrics-port
          protocol: TCP
        {{- end }}
        resources:
          {{- toYaml .Values.actionsMetricsServer.resources | nindent 12 }}
        securityContext:
          {{- toYaml .Values.actionsMetricsServer.securityContext | nindent 12 }}
      {{- if .Values.actionsMetrics.proxy.enabled }}
      - args:
        - "--secure-listen-address=0.0.0.0:{{ .Values.actionsMetrics.port }}"
        - "--upstream=http://127.0.0.1:8080/"
        - "--logtostderr=true"
        - "--v=10"
        image: "{{ .Values.actionsMetrics.proxy.image.repository }}:{{ .Values.actionsMetrics.proxy.image.tag }}"
        name: kube-rbac-proxy
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.actionsMetrics.port }}
          name: metrics-port
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.actionsMetricsServer.terminationGracePeriodSeconds }}
      {{- with .Values.actionsMetricsServer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.actionsMetricsServer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.actionsMetricsServer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.actionsMetricsServer.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
