{{- if .Values.rbac.aggregateRoles.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "actions-runner-controller.aggregateEditRoleName" . }}
  labels:
    {{- include "actions-runner-controller.labels" . | nindent 4 }}
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
- apiGroups:
  - actions.summerwind.dev
  resources:
  - runnerdeployments
  - runnerreplicasets
  - runnersets
  - horizontalrunnerautoscalers
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - actions.summerwind.dev
  resources:
  - runners
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
{{- end }}
