apiVersion: v1
kind: Service
metadata:
  name: {{ include "actions-runner-controller.webhookServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "actions-runner-controller.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 443
      targetPort: {{ .Values.webhookPort }}
      protocol: TCP
      name: https
  selector:
    {{- include "actions-runner-controller.selectorLabels" . | nindent 4 }}
