// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package metrics

import (
	"context"
	"time"

	"github.com/actions/scaleset"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRecorder creates a new instance of MockRecorder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRecorder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRecorder {
	mock := &MockRecorder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRecorder is an autogenerated mock type for the Recorder type
type MockRecorder struct {
	mock.Mock
}

type MockRecorder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRecorder) EXPECT() *MockRecorder_Expecter {
	return &MockRecorder_Expecter{mock: &_m.Mock}
}

// RecordDesiredRunners provides a mock function for the type MockRecorder
func (_mock *MockRecorder) RecordDesiredRunners(count int) {
	_mock.Called(count)
	return
}

// MockRecorder_RecordDesiredRunners_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordDesiredRunners'
type MockRecorder_RecordDesiredRunners_Call struct {
	*mock.Call
}

// RecordDesiredRunners is a helper method to define mock.On call
//   - count int
func (_e *MockRecorder_Expecter) RecordDesiredRunners(count interface{}) *MockRecorder_RecordDesiredRunners_Call {
	return &MockRecorder_RecordDesiredRunners_Call{Call: _e.mock.On("RecordDesiredRunners", count)}
}

func (_c *MockRecorder_RecordDesiredRunners_Call) Run(run func(count int)) *MockRecorder_RecordDesiredRunners_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRecorder_RecordDesiredRunners_Call) Return() *MockRecorder_RecordDesiredRunners_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRecorder_RecordDesiredRunners_Call) RunAndReturn(run func(count int)) *MockRecorder_RecordDesiredRunners_Call {
	_c.Run(run)
	return _c
}

// RecordJobCompleted provides a mock function for the type MockRecorder
func (_mock *MockRecorder) RecordJobCompleted(msg *scaleset.JobCompleted) {
	_mock.Called(msg)
	return
}

// MockRecorder_RecordJobCompleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordJobCompleted'
type MockRecorder_RecordJobCompleted_Call struct {
	*mock.Call
}

// RecordJobCompleted is a helper method to define mock.On call
//   - msg *scaleset.JobCompleted
func (_e *MockRecorder_Expecter) RecordJobCompleted(msg interface{}) *MockRecorder_RecordJobCompleted_Call {
	return &MockRecorder_RecordJobCompleted_Call{Call: _e.mock.On("RecordJobCompleted", msg)}
}

func (_c *MockRecorder_RecordJobCompleted_Call) Run(run func(msg *scaleset.JobCompleted)) *MockRecorder_RecordJobCompleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *scaleset.JobCompleted
		if args[0] != nil {
			arg0 = args[0].(*scaleset.JobCompleted)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRecorder_RecordJobCompleted_Call) Return() *MockRecorder_RecordJobCompleted_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRecorder_RecordJobCompleted_Call) RunAndReturn(run func(msg *scaleset.JobCompleted)) *MockRecorder_RecordJobCompleted_Call {
	_c.Run(run)
	return _c
}

// RecordJobStarted provides a mock function for the type MockRecorder
func (_mock *MockRecorder) RecordJobStarted(msg *scaleset.JobStarted) {
	_mock.Called(msg)
	return
}

// MockRecorder_RecordJobStarted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordJobStarted'
type MockRecorder_RecordJobStarted_Call struct {
	*mock.Call
}

// RecordJobStarted is a helper method to define mock.On call
//   - msg *scaleset.JobStarted
func (_e *MockRecorder_Expecter) RecordJobStarted(msg interface{}) *MockRecorder_RecordJobStarted_Call {
	return &MockRecorder_RecordJobStarted_Call{Call: _e.mock.On("RecordJobStarted", msg)}
}

func (_c *MockRecorder_RecordJobStarted_Call) Run(run func(msg *scaleset.JobStarted)) *MockRecorder_RecordJobStarted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *scaleset.JobStarted
		if args[0] != nil {
			arg0 = args[0].(*scaleset.JobStarted)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRecorder_RecordJobStarted_Call) Return() *MockRecorder_RecordJobStarted_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRecorder_RecordJobStarted_Call) RunAndReturn(run func(msg *scaleset.JobStarted)) *MockRecorder_RecordJobStarted_Call {
	_c.Run(run)
	return _c
}

// RecordStatic provides a mock function for the type MockRecorder
func (_mock *MockRecorder) RecordStatic(min int, max int) {
	_mock.Called(min, max)
	return
}

// MockRecorder_RecordStatic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordStatic'
type MockRecorder_RecordStatic_Call struct {
	*mock.Call
}

// RecordStatic is a helper method to define mock.On call
//   - min int
//   - max int
func (_e *MockRecorder_Expecter) RecordStatic(min interface{}, max interface{}) *MockRecorder_RecordStatic_Call {
	return &MockRecorder_RecordStatic_Call{Call: _e.mock.On("RecordStatic", min, max)}
}

func (_c *MockRecorder_RecordStatic_Call) Run(run func(min int, max int)) *MockRecorder_RecordStatic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRecorder_RecordStatic_Call) Return() *MockRecorder_RecordStatic_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRecorder_RecordStatic_Call) RunAndReturn(run func(min int, max int)) *MockRecorder_RecordStatic_Call {
	_c.Run(run)
	return _c
}

// RecordStatistics provides a mock function for the type MockRecorder
func (_mock *MockRecorder) RecordStatistics(stats *scaleset.RunnerScaleSetStatistic) {
	_mock.Called(stats)
	return
}

// MockRecorder_RecordStatistics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordStatistics'
type MockRecorder_RecordStatistics_Call struct {
	*mock.Call
}

// RecordStatistics is a helper method to define mock.On call
//   - stats *scaleset.RunnerScaleSetStatistic
func (_e *MockRecorder_Expecter) RecordStatistics(stats interface{}) *MockRecorder_RecordStatistics_Call {
	return &MockRecorder_RecordStatistics_Call{Call: _e.mock.On("RecordStatistics", stats)}
}

func (_c *MockRecorder_RecordStatistics_Call) Run(run func(stats *scaleset.RunnerScaleSetStatistic)) *MockRecorder_RecordStatistics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *scaleset.RunnerScaleSetStatistic
		if args[0] != nil {
			arg0 = args[0].(*scaleset.RunnerScaleSetStatistic)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRecorder_RecordStatistics_Call) Return() *MockRecorder_RecordStatistics_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRecorder_RecordStatistics_Call) RunAndReturn(run func(stats *scaleset.RunnerScaleSetStatistic)) *MockRecorder_RecordStatistics_Call {
	_c.Run(run)
	return _c
}

// NewMockCapacityRecorder creates a new instance of MockCapacityRecorder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCapacityRecorder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCapacityRecorder {
	mock := &MockCapacityRecorder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCapacityRecorder is an autogenerated mock type for the CapacityRecorder type
type MockCapacityRecorder struct {
	mock.Mock
}

type MockCapacityRecorder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCapacityRecorder) EXPECT() *MockCapacityRecorder_Expecter {
	return &MockCapacityRecorder_Expecter{mock: &_m.Mock}
}

// IncHUDRequests provides a mock function for the type MockCapacityRecorder
func (_mock *MockCapacityRecorder) IncHUDRequests(result string) {
	_mock.Called(result)
	return
}

// MockCapacityRecorder_IncHUDRequests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncHUDRequests'
type MockCapacityRecorder_IncHUDRequests_Call struct {
	*mock.Call
}

// IncHUDRequests is a helper method to define mock.On call
//   - result string
func (_e *MockCapacityRecorder_Expecter) IncHUDRequests(result interface{}) *MockCapacityRecorder_IncHUDRequests_Call {
	return &MockCapacityRecorder_IncHUDRequests_Call{Call: _e.mock.On("IncHUDRequests", result)}
}

func (_c *MockCapacityRecorder_IncHUDRequests_Call) Run(run func(result string)) *MockCapacityRecorder_IncHUDRequests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCapacityRecorder_IncHUDRequests_Call) Return() *MockCapacityRecorder_IncHUDRequests_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCapacityRecorder_IncHUDRequests_Call) RunAndReturn(run func(result string)) *MockCapacityRecorder_IncHUDRequests_Call {
	_c.Run(run)
	return _c
}

// IncPairCreates provides a mock function for the type MockCapacityRecorder
func (_mock *MockCapacityRecorder) IncPairCreates(result string) {
	_mock.Called(result)
	return
}

// MockCapacityRecorder_IncPairCreates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncPairCreates'
type MockCapacityRecorder_IncPairCreates_Call struct {
	*mock.Call
}

// IncPairCreates is a helper method to define mock.On call
//   - result string
func (_e *MockCapacityRecorder_Expecter) IncPairCreates(result interface{}) *MockCapacityRecorder_IncPairCreates_Call {
	return &MockCapacityRecorder_IncPairCreates_Call{Call: _e.mock.On("IncPairCreates", result)}
}

func (_c *MockCapacityRecorder_IncPairCreates_Call) Run(run func(result string)) *MockCapacityRecorder_IncPairCreates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCapacityRecorder_IncPairCreates_Call) Return() *MockCapacityRecorder_IncPairCreates_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCapacityRecorder_IncPairCreates_Call) RunAndReturn(run func(result string)) *MockCapacityRecorder_IncPairCreates_Call {
	_c.Run(run)
	return _c
}

// IncPairDeletes provides a mock function for the type MockCapacityRecorder
func (_mock *MockCapacityRecorder) IncPairDeletes(reason string, result string) {
	_mock.Called(reason, result)
	return
}

// MockCapacityRecorder_IncPairDeletes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncPairDeletes'
type MockCapacityRecorder_IncPairDeletes_Call struct {
	*mock.Call
}

// IncPairDeletes is a helper method to define mock.On call
//   - reason string
//   - result string
func (_e *MockCapacityRecorder_Expecter) IncPairDeletes(reason interface{}, result interface{}) *MockCapacityRecorder_IncPairDeletes_Call {
	return &MockCapacityRecorder_IncPairDeletes_Call{Call: _e.mock.On("IncPairDeletes", reason, result)}
}

func (_c *MockCapacityRecorder_IncPairDeletes_Call) Run(run func(reason string, result string)) *MockCapacityRecorder_IncPairDeletes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCapacityRecorder_IncPairDeletes_Call) Return() *MockCapacityRecorder_IncPairDeletes_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCapacityRecorder_IncPairDeletes_Call) RunAndReturn(run func(reason string, result string)) *MockCapacityRecorder_IncPairDeletes_Call {
	_c.Run(run)
	return _c
}

// IncReconcileSkips provides a mock function for the type MockCapacityRecorder
func (_mock *MockCapacityRecorder) IncReconcileSkips(reason string) {
	_mock.Called(reason)
	return
}

// MockCapacityRecorder_IncReconcileSkips_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncReconcileSkips'
type MockCapacityRecorder_IncReconcileSkips_Call struct {
	*mock.Call
}

// IncReconcileSkips is a helper method to define mock.On call
//   - reason string
func (_e *MockCapacityRecorder_Expecter) IncReconcileSkips(reason interface{}) *MockCapacityRecorder_IncReconcileSkips_Call {
	return &MockCapacityRecorder_IncReconcileSkips_Call{Call: _e.mock.On("IncReconcileSkips", reason)}
}

func (_c *MockCapacityRecorder_IncReconcileSkips_Call) Run(run func(reason string)) *MockCapacityRecorder_IncReconcileSkips_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCapacityRecorder_IncReconcileSkips_Call) Return() *MockCapacityRecorder_IncReconcileSkips_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCapacityRecorder_IncReconcileSkips_Call) RunAndReturn(run func(reason string)) *MockCapacityRecorder_IncReconcileSkips_Call {
	_c.Run(run)
	return _c
}

// ObserveHUDRequest provides a mock function for the type MockCapacityRecorder
func (_mock *MockCapacityRecorder) ObserveHUDRequest(result string, d time.Duration) {
	_mock.Called(result, d)
	return
}

// MockCapacityRecorder_ObserveHUDRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ObserveHUDRequest'
type MockCapacityRecorder_ObserveHUDRequest_Call struct {
	*mock.Call
}

// ObserveHUDRequest is a helper method to define mock.On call
//   - result string
//   - d time.Duration
func (_e *MockCapacityRecorder_Expecter) ObserveHUDRequest(result interface{}, d interface{}) *MockCapacityRecorder_ObserveHUDRequest_Call {
	return &MockCapacityRecorder_ObserveHUDRequest_Call{Call: _e.mock.On("ObserveHUDRequest", result, d)}
}

func (_c *MockCapacityRecorder_ObserveHUDRequest_Call) Run(run func(result string, d time.Duration)) *MockCapacityRecorder_ObserveHUDRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCapacityRecorder_ObserveHUDRequest_Call) Return() *MockCapacityRecorder_ObserveHUDRequest_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCapacityRecorder_ObserveHUDRequest_Call) RunAndReturn(run func(result string, d time.Duration)) *MockCapacityRecorder_ObserveHUDRequest_Call {
	_c.Run(run)
	return _c
}

// ObserveReconcileDuration provides a mock function for the type MockCapacityRecorder
func (_mock *MockCapacityRecorder) ObserveReconcileDuration(phase string, d time.Duration) {
	_mock.Called(phase, d)
	return
}

// MockCapacityRecorder_ObserveReconcileDuration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ObserveReconcileDuration'
type MockCapacityRecorder_ObserveReconcileDuration_Call struct {
	*mock.Call
}

// ObserveReconcileDuration is a helper method to define mock.On call
//   - phase string
//   - d time.Duration
func (_e *MockCapacityRecorder_Expecter) ObserveReconcileDuration(phase interface{}, d interface{}) *MockCapacityRecorder_ObserveReconcileDuration_Call {
	return &MockCapacityRecorder_ObserveReconcileDuration_Call{Call: _e.mock.On("ObserveReconcileDuration", phase, d)}
}

func (_c *MockCapacityRecorder_ObserveReconcileDuration_Call) Run(run func(phase string, d time.Duration)) *MockCapacityRecorder_ObserveReconcileDuration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCapacityRecorder_ObserveReconcileDuration_Call) Return() *MockCapacityRecorder_ObserveReconcileDuration_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCapacityRecorder_ObserveReconcileDuration_Call) RunAndReturn(run func(phase string, d time.Duration)) *MockCapacityRecorder_ObserveReconcileDuration_Call {
	_c.Run(run)
	return _c
}

// SetAdvertisedMaxRunners provides a mock function for the type MockCapacityRecorder
func (_mock *MockCapacityRecorder) SetAdvertisedMaxRunners(value int) {
	_mock.Called(value)
	return
}

// MockCapacityRecorder_SetAdvertisedMaxRunners_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAdvertisedMaxRunners'
type MockCapacityRecorder_SetAdvertisedMaxRunners_Call struct {
	*mock.Call
}

// SetAdvertisedMaxRunners is a helper method to define mock.On call
//   - value int
func (_e *MockCapacityRecorder_Expecter) SetAdvertisedMaxRunners(value interface{}) *MockCapacityRecorder_SetAdvertisedMaxRunners_Call {
	return &MockCapacityRecorder_SetAdvertisedMaxRunners_Call{Call: _e.mock.On("SetAdvertisedMaxRunners", value)}
}

func (_c *MockCapacityRecorder_SetAdvertisedMaxRunners_Call) Run(run func(value int)) *MockCapacityRecorder_SetAdvertisedMaxRunners_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCapacityRecorder_SetAdvertisedMaxRunners_Call) Return() *MockCapacityRecorder_SetAdvertisedMaxRunners_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCapacityRecorder_SetAdvertisedMaxRunners_Call) RunAndReturn(run func(value int)) *MockCapacityRecorder_SetAdvertisedMaxRunners_Call {
	_c.Run(run)
	return _c
}

// SetDesiredPairs provides a mock function for the type MockCapacityRecorder
func (_mock *MockCapacityRecorder) SetDesiredPairs(value int) {
	_mock.Called(value)
	return
}

// MockCapacityRecorder_SetDesiredPairs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDesiredPairs'
type MockCapacityRecorder_SetDesiredPairs_Call struct {
	*mock.Call
}

// SetDesiredPairs is a helper method to define mock.On call
//   - value int
func (_e *MockCapacityRecorder_Expecter) SetDesiredPairs(value interface{}) *MockCapacityRecorder_SetDesiredPairs_Call {
	return &MockCapacityRecorder_SetDesiredPairs_Call{Call: _e.mock.On("SetDesiredPairs", value)}
}

func (_c *MockCapacityRecorder_SetDesiredPairs_Call) Run(run func(value int)) *MockCapacityRecorder_SetDesiredPairs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCapacityRecorder_SetDesiredPairs_Call) Return() *MockCapacityRecorder_SetDesiredPairs_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCapacityRecorder_SetDesiredPairs_Call) RunAndReturn(run func(value int)) *MockCapacityRecorder_SetDesiredPairs_Call {
	_c.Run(run)
	return _c
}

// SetHUDEnabled provides a mock function for the type MockCapacityRecorder
func (_mock *MockCapacityRecorder) SetHUDEnabled(enabled bool) {
	_mock.Called(enabled)
	return
}

// MockCapacityRecorder_SetHUDEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHUDEnabled'
type MockCapacityRecorder_SetHUDEnabled_Call struct {
	*mock.Call
}

// SetHUDEnabled is a helper method to define mock.On call
//   - enabled bool
func (_e *MockCapacityRecorder_Expecter) SetHUDEnabled(enabled interface{}) *MockCapacityRecorder_SetHUDEnabled_Call {
	return &MockCapacityRecorder_SetHUDEnabled_Call{Call: _e.mock.On("SetHUDEnabled", enabled)}
}

func (_c *MockCapacityRecorder_SetHUDEnabled_Call) Run(run func(enabled bool)) *MockCapacityRecorder_SetHUDEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCapacityRecorder_SetHUDEnabled_Call) Return() *MockCapacityRecorder_SetHUDEnabled_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCapacityRecorder_SetHUDEnabled_Call) RunAndReturn(run func(enabled bool)) *MockCapacityRecorder_SetHUDEnabled_Call {
	_c.Run(run)
	return _c
}

// SetPairs provides a mock function for the type MockCapacityRecorder
func (_mock *MockCapacityRecorder) SetPairs(value int) {
	_mock.Called(value)
	return
}

// MockCapacityRecorder_SetPairs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPairs'
type MockCapacityRecorder_SetPairs_Call struct {
	*mock.Call
}

// SetPairs is a helper method to define mock.On call
//   - value int
func (_e *MockCapacityRecorder_Expecter) SetPairs(value interface{}) *MockCapacityRecorder_SetPairs_Call {
	return &MockCapacityRecorder_SetPairs_Call{Call: _e.mock.On("SetPairs", value)}
}

func (_c *MockCapacityRecorder_SetPairs_Call) Run(run func(value int)) *MockCapacityRecorder_SetPairs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCapacityRecorder_SetPairs_Call) Return() *MockCapacityRecorder_SetPairs_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCapacityRecorder_SetPairs_Call) RunAndReturn(run func(value int)) *MockCapacityRecorder_SetPairs_Call {
	_c.Run(run)
	return _c
}

// SetPlaceholderPods provides a mock function for the type MockCapacityRecorder
func (_mock *MockCapacityRecorder) SetPlaceholderPods(role string, phase string, value int) {
	_mock.Called(role, phase, value)
	return
}

// MockCapacityRecorder_SetPlaceholderPods_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPlaceholderPods'
type MockCapacityRecorder_SetPlaceholderPods_Call struct {
	*mock.Call
}

// SetPlaceholderPods is a helper method to define mock.On call
//   - role string
//   - phase string
//   - value int
func (_e *MockCapacityRecorder_Expecter) SetPlaceholderPods(role interface{}, phase interface{}, value interface{}) *MockCapacityRecorder_SetPlaceholderPods_Call {
	return &MockCapacityRecorder_SetPlaceholderPods_Call{Call: _e.mock.On("SetPlaceholderPods", role, phase, value)}
}

func (_c *MockCapacityRecorder_SetPlaceholderPods_Call) Run(run func(role string, phase string, value int)) *MockCapacityRecorder_SetPlaceholderPods_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCapacityRecorder_SetPlaceholderPods_Call) Return() *MockCapacityRecorder_SetPlaceholderPods_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCapacityRecorder_SetPlaceholderPods_Call) RunAndReturn(run func(role string, phase string, value int)) *MockCapacityRecorder_SetPlaceholderPods_Call {
	_c.Run(run)
	return _c
}

// SetProactiveCapacity provides a mock function for the type MockCapacityRecorder
func (_mock *MockCapacityRecorder) SetProactiveCapacity(value int) {
	_mock.Called(value)
	return
}

// MockCapacityRecorder_SetProactiveCapacity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetProactiveCapacity'
type MockCapacityRecorder_SetProactiveCapacity_Call struct {
	*mock.Call
}

// SetProactiveCapacity is a helper method to define mock.On call
//   - value int
func (_e *MockCapacityRecorder_Expecter) SetProactiveCapacity(value interface{}) *MockCapacityRecorder_SetProactiveCapacity_Call {
	return &MockCapacityRecorder_SetProactiveCapacity_Call{Call: _e.mock.On("SetProactiveCapacity", value)}
}

func (_c *MockCapacityRecorder_SetProactiveCapacity_Call) Run(run func(value int)) *MockCapacityRecorder_SetProactiveCapacity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCapacityRecorder_SetProactiveCapacity_Call) Return() *MockCapacityRecorder_SetProactiveCapacity_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCapacityRecorder_SetProactiveCapacity_Call) RunAndReturn(run func(value int)) *MockCapacityRecorder_SetProactiveCapacity_Call {
	_c.Run(run)
	return _c
}

// SetQueuedJobs provides a mock function for the type MockCapacityRecorder
func (_mock *MockCapacityRecorder) SetQueuedJobs(value int) {
	_mock.Called(value)
	return
}

// MockCapacityRecorder_SetQueuedJobs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetQueuedJobs'
type MockCapacityRecorder_SetQueuedJobs_Call struct {
	*mock.Call
}

// SetQueuedJobs is a helper method to define mock.On call
//   - value int
func (_e *MockCapacityRecorder_Expecter) SetQueuedJobs(value interface{}) *MockCapacityRecorder_SetQueuedJobs_Call {
	return &MockCapacityRecorder_SetQueuedJobs_Call{Call: _e.mock.On("SetQueuedJobs", value)}
}

func (_c *MockCapacityRecorder_SetQueuedJobs_Call) Run(run func(value int)) *MockCapacityRecorder_SetQueuedJobs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCapacityRecorder_SetQueuedJobs_Call) Return() *MockCapacityRecorder_SetQueuedJobs_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCapacityRecorder_SetQueuedJobs_Call) RunAndReturn(run func(value int)) *MockCapacityRecorder_SetQueuedJobs_Call {
	_c.Run(run)
	return _c
}

// SetReconcileLastSuccess provides a mock function for the type MockCapacityRecorder
func (_mock *MockCapacityRecorder) SetReconcileLastSuccess(phase string, t time.Time) {
	_mock.Called(phase, t)
	return
}

// MockCapacityRecorder_SetReconcileLastSuccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetReconcileLastSuccess'
type MockCapacityRecorder_SetReconcileLastSuccess_Call struct {
	*mock.Call
}

// SetReconcileLastSuccess is a helper method to define mock.On call
//   - phase string
//   - t time.Time
func (_e *MockCapacityRecorder_Expecter) SetReconcileLastSuccess(phase interface{}, t interface{}) *MockCapacityRecorder_SetReconcileLastSuccess_Call {
	return &MockCapacityRecorder_SetReconcileLastSuccess_Call{Call: _e.mock.On("SetReconcileLastSuccess", phase, t)}
}

func (_c *MockCapacityRecorder_SetReconcileLastSuccess_Call) Run(run func(phase string, t time.Time)) *MockCapacityRecorder_SetReconcileLastSuccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCapacityRecorder_SetReconcileLastSuccess_Call) Return() *MockCapacityRecorder_SetReconcileLastSuccess_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCapacityRecorder_SetReconcileLastSuccess_Call) RunAndReturn(run func(phase string, t time.Time)) *MockCapacityRecorder_SetReconcileLastSuccess_Call {
	_c.Run(run)
	return _c
}

// SetRunningPairs provides a mock function for the type MockCapacityRecorder
func (_mock *MockCapacityRecorder) SetRunningPairs(value int) {
	_mock.Called(value)
	return
}

// MockCapacityRecorder_SetRunningPairs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetRunningPairs'
type MockCapacityRecorder_SetRunningPairs_Call struct {
	*mock.Call
}

// SetRunningPairs is a helper method to define mock.On call
//   - value int
func (_e *MockCapacityRecorder_Expecter) SetRunningPairs(value interface{}) *MockCapacityRecorder_SetRunningPairs_Call {
	return &MockCapacityRecorder_SetRunningPairs_Call{Call: _e.mock.On("SetRunningPairs", value)}
}

func (_c *MockCapacityRecorder_SetRunningPairs_Call) Run(run func(value int)) *MockCapacityRecorder_SetRunningPairs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCapacityRecorder_SetRunningPairs_Call) Return() *MockCapacityRecorder_SetRunningPairs_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCapacityRecorder_SetRunningPairs_Call) RunAndReturn(run func(value int)) *MockCapacityRecorder_SetRunningPairs_Call {
	_c.Run(run)
	return _c
}

// NewMockServerExporter creates a new instance of MockServerExporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServerExporter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServerExporter {
	mock := &MockServerExporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServerExporter is an autogenerated mock type for the ServerExporter type
type MockServerExporter struct {
	mock.Mock
}

type MockServerExporter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServerExporter) EXPECT() *MockServerExporter_Expecter {
	return &MockServerExporter_Expecter{mock: &_m.Mock}
}

// IncHUDRequests provides a mock function for the type MockServerExporter
func (_mock *MockServerExporter) IncHUDRequests(result string) {
	_mock.Called(result)
	return
}

// MockServerExporter_IncHUDRequests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncHUDRequests'
type MockServerExporter_IncHUDRequests_Call struct {
	*mock.Call
}

// IncHUDRequests is a helper method to define mock.On call
//   - result string
func (_e *MockServerExporter_Expecter) IncHUDRequests(result interface{}) *MockServerExporter_IncHUDRequests_Call {
	return &MockServerExporter_IncHUDRequests_Call{Call: _e.mock.On("IncHUDRequests", result)}
}

func (_c *MockServerExporter_IncHUDRequests_Call) Run(run func(result string)) *MockServerExporter_IncHUDRequests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServerExporter_IncHUDRequests_Call) Return() *MockServerExporter_IncHUDRequests_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerExporter_IncHUDRequests_Call) RunAndReturn(run func(result string)) *MockServerExporter_IncHUDRequests_Call {
	_c.Run(run)
	return _c
}

// IncPairCreates provides a mock function for the type MockServerExporter
func (_mock *MockServerExporter) IncPairCreates(result string) {
	_mock.Called(result)
	return
}

// MockServerExporter_IncPairCreates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncPairCreates'
type MockServerExporter_IncPairCreates_Call struct {
	*mock.Call
}

// IncPairCreates is a helper method to define mock.On call
//   - result string
func (_e *MockServerExporter_Expecter) IncPairCreates(result interface{}) *MockServerExporter_IncPairCreates_Call {
	return &MockServerExporter_IncPairCreates_Call{Call: _e.mock.On("IncPairCreates", result)}
}

func (_c *MockServerExporter_IncPairCreates_Call) Run(run func(result string)) *MockServerExporter_IncPairCreates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServerExporter_IncPairCreates_Call) Return() *MockServerExporter_IncPairCreates_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerExporter_IncPairCreates_Call) RunAndReturn(run func(result string)) *MockServerExporter_IncPairCreates_Call {
	_c.Run(run)
	return _c
}

// IncPairDeletes provides a mock function for the type MockServerExporter
func (_mock *MockServerExporter) IncPairDeletes(reason string, result string) {
	_mock.Called(reason, result)
	return
}

// MockServerExporter_IncPairDeletes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncPairDeletes'
type MockServerExporter_IncPairDeletes_Call struct {
	*mock.Call
}

// IncPairDeletes is a helper method to define mock.On call
//   - reason string
//   - result string
func (_e *MockServerExporter_Expecter) IncPairDeletes(reason interface{}, result interface{}) *MockServerExporter_IncPairDeletes_Call {
	return &MockServerExporter_IncPairDeletes_Call{Call: _e.mock.On("IncPairDeletes", reason, result)}
}

func (_c *MockServerExporter_IncPairDeletes_Call) Run(run func(reason string, result string)) *MockServerExporter_IncPairDeletes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServerExporter_IncPairDeletes_Call) Return() *MockServerExporter_IncPairDeletes_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerExporter_IncPairDeletes_Call) RunAndReturn(run func(reason string, result string)) *MockServerExporter_IncPairDeletes_Call {
	_c.Run(run)
	return _c
}

// IncReconcileSkips provides a mock function for the type MockServerExporter
func (_mock *MockServerExporter) IncReconcileSkips(reason string) {
	_mock.Called(reason)
	return
}

// MockServerExporter_IncReconcileSkips_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncReconcileSkips'
type MockServerExporter_IncReconcileSkips_Call struct {
	*mock.Call
}

// IncReconcileSkips is a helper method to define mock.On call
//   - reason string
func (_e *MockServerExporter_Expecter) IncReconcileSkips(reason interface{}) *MockServerExporter_IncReconcileSkips_Call {
	return &MockServerExporter_IncReconcileSkips_Call{Call: _e.mock.On("IncReconcileSkips", reason)}
}

func (_c *MockServerExporter_IncReconcileSkips_Call) Run(run func(reason string)) *MockServerExporter_IncReconcileSkips_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServerExporter_IncReconcileSkips_Call) Return() *MockServerExporter_IncReconcileSkips_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerExporter_IncReconcileSkips_Call) RunAndReturn(run func(reason string)) *MockServerExporter_IncReconcileSkips_Call {
	_c.Run(run)
	return _c
}

// ListenAndServe provides a mock function for the type MockServerExporter
func (_mock *MockServerExporter) ListenAndServe(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListenAndServe")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServerExporter_ListenAndServe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListenAndServe'
type MockServerExporter_ListenAndServe_Call struct {
	*mock.Call
}

// ListenAndServe is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockServerExporter_Expecter) ListenAndServe(ctx interface{}) *MockServerExporter_ListenAndServe_Call {
	return &MockServerExporter_ListenAndServe_Call{Call: _e.mock.On("ListenAndServe", ctx)}
}

func (_c *MockServerExporter_ListenAndServe_Call) Run(run func(ctx context.Context)) *MockServerExporter_ListenAndServe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServerExporter_ListenAndServe_Call) Return(err error) *MockServerExporter_ListenAndServe_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServerExporter_ListenAndServe_Call) RunAndReturn(run func(ctx context.Context) error) *MockServerExporter_ListenAndServe_Call {
	_c.Call.Return(run)
	return _c
}

// ObserveHUDRequest provides a mock function for the type MockServerExporter
func (_mock *MockServerExporter) ObserveHUDRequest(result string, d time.Duration) {
	_mock.Called(result, d)
	return
}

// MockServerExporter_ObserveHUDRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ObserveHUDRequest'
type MockServerExporter_ObserveHUDRequest_Call struct {
	*mock.Call
}

// ObserveHUDRequest is a helper method to define mock.On call
//   - result string
//   - d time.Duration
func (_e *MockServerExporter_Expecter) ObserveHUDRequest(result interface{}, d interface{}) *MockServerExporter_ObserveHUDRequest_Call {
	return &MockServerExporter_ObserveHUDRequest_Call{Call: _e.mock.On("ObserveHUDRequest", result, d)}
}

func (_c *MockServerExporter_ObserveHUDRequest_Call) Run(run func(result string, d time.Duration)) *MockServerExporter_ObserveHUDRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServerExporter_ObserveHUDRequest_Call) Return() *MockServerExporter_ObserveHUDRequest_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerExporter_ObserveHUDRequest_Call) RunAndReturn(run func(result string, d time.Duration)) *MockServerExporter_ObserveHUDRequest_Call {
	_c.Run(run)
	return _c
}

// ObserveReconcileDuration provides a mock function for the type MockServerExporter
func (_mock *MockServerExporter) ObserveReconcileDuration(phase string, d time.Duration) {
	_mock.Called(phase, d)
	return
}

// MockServerExporter_ObserveReconcileDuration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ObserveReconcileDuration'
type MockServerExporter_ObserveReconcileDuration_Call struct {
	*mock.Call
}

// ObserveReconcileDuration is a helper method to define mock.On call
//   - phase string
//   - d time.Duration
func (_e *MockServerExporter_Expecter) ObserveReconcileDuration(phase interface{}, d interface{}) *MockServerExporter_ObserveReconcileDuration_Call {
	return &MockServerExporter_ObserveReconcileDuration_Call{Call: _e.mock.On("ObserveReconcileDuration", phase, d)}
}

func (_c *MockServerExporter_ObserveReconcileDuration_Call) Run(run func(phase string, d time.Duration)) *MockServerExporter_ObserveReconcileDuration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServerExporter_ObserveReconcileDuration_Call) Return() *MockServerExporter_ObserveReconcileDuration_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerExporter_ObserveReconcileDuration_Call) RunAndReturn(run func(phase string, d time.Duration)) *MockServerExporter_ObserveReconcileDuration_Call {
	_c.Run(run)
	return _c
}

// RecordDesiredRunners provides a mock function for the type MockServerExporter
func (_mock *MockServerExporter) RecordDesiredRunners(count int) {
	_mock.Called(count)
	return
}

// MockServerExporter_RecordDesiredRunners_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordDesiredRunners'
type MockServerExporter_RecordDesiredRunners_Call struct {
	*mock.Call
}

// RecordDesiredRunners is a helper method to define mock.On call
//   - count int
func (_e *MockServerExporter_Expecter) RecordDesiredRunners(count interface{}) *MockServerExporter_RecordDesiredRunners_Call {
	return &MockServerExporter_RecordDesiredRunners_Call{Call: _e.mock.On("RecordDesiredRunners", count)}
}

func (_c *MockServerExporter_RecordDesiredRunners_Call) Run(run func(count int)) *MockServerExporter_RecordDesiredRunners_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServerExporter_RecordDesiredRunners_Call) Return() *MockServerExporter_RecordDesiredRunners_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerExporter_RecordDesiredRunners_Call) RunAndReturn(run func(count int)) *MockServerExporter_RecordDesiredRunners_Call {
	_c.Run(run)
	return _c
}

// RecordJobCompleted provides a mock function for the type MockServerExporter
func (_mock *MockServerExporter) RecordJobCompleted(msg *scaleset.JobCompleted) {
	_mock.Called(msg)
	return
}

// MockServerExporter_RecordJobCompleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordJobCompleted'
type MockServerExporter_RecordJobCompleted_Call struct {
	*mock.Call
}

// RecordJobCompleted is a helper method to define mock.On call
//   - msg *scaleset.JobCompleted
func (_e *MockServerExporter_Expecter) RecordJobCompleted(msg interface{}) *MockServerExporter_RecordJobCompleted_Call {
	return &MockServerExporter_RecordJobCompleted_Call{Call: _e.mock.On("RecordJobCompleted", msg)}
}

func (_c *MockServerExporter_RecordJobCompleted_Call) Run(run func(msg *scaleset.JobCompleted)) *MockServerExporter_RecordJobCompleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *scaleset.JobCompleted
		if args[0] != nil {
			arg0 = args[0].(*scaleset.JobCompleted)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServerExporter_RecordJobCompleted_Call) Return() *MockServerExporter_RecordJobCompleted_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerExporter_RecordJobCompleted_Call) RunAndReturn(run func(msg *scaleset.JobCompleted)) *MockServerExporter_RecordJobCompleted_Call {
	_c.Run(run)
	return _c
}

// RecordJobStarted provides a mock function for the type MockServerExporter
func (_mock *MockServerExporter) RecordJobStarted(msg *scaleset.JobStarted) {
	_mock.Called(msg)
	return
}

// MockServerExporter_RecordJobStarted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordJobStarted'
type MockServerExporter_RecordJobStarted_Call struct {
	*mock.Call
}

// RecordJobStarted is a helper method to define mock.On call
//   - msg *scaleset.JobStarted
func (_e *MockServerExporter_Expecter) RecordJobStarted(msg interface{}) *MockServerExporter_RecordJobStarted_Call {
	return &MockServerExporter_RecordJobStarted_Call{Call: _e.mock.On("RecordJobStarted", msg)}
}

func (_c *MockServerExporter_RecordJobStarted_Call) Run(run func(msg *scaleset.JobStarted)) *MockServerExporter_RecordJobStarted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *scaleset.JobStarted
		if args[0] != nil {
			arg0 = args[0].(*scaleset.JobStarted)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServerExporter_RecordJobStarted_Call) Return() *MockServerExporter_RecordJobStarted_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerExporter_RecordJobStarted_Call) RunAndReturn(run func(msg *scaleset.JobStarted)) *MockServerExporter_RecordJobStarted_Call {
	_c.Run(run)
	return _c
}

// RecordStatic provides a mock function for the type MockServerExporter
func (_mock *MockServerExporter) RecordStatic(min int, max int) {
	_mock.Called(min, max)
	return
}

// MockServerExporter_RecordStatic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordStatic'
type MockServerExporter_RecordStatic_Call struct {
	*mock.Call
}

// RecordStatic is a helper method to define mock.On call
//   - min int
//   - max int
func (_e *MockServerExporter_Expecter) RecordStatic(min interface{}, max interface{}) *MockServerExporter_RecordStatic_Call {
	return &MockServerExporter_RecordStatic_Call{Call: _e.mock.On("RecordStatic", min, max)}
}

func (_c *MockServerExporter_RecordStatic_Call) Run(run func(min int, max int)) *MockServerExporter_RecordStatic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServerExporter_RecordStatic_Call) Return() *MockServerExporter_RecordStatic_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerExporter_RecordStatic_Call) RunAndReturn(run func(min int, max int)) *MockServerExporter_RecordStatic_Call {
	_c.Run(run)
	return _c
}

// RecordStatistics provides a mock function for the type MockServerExporter
func (_mock *MockServerExporter) RecordStatistics(stats *scaleset.RunnerScaleSetStatistic) {
	_mock.Called(stats)
	return
}

// MockServerExporter_RecordStatistics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordStatistics'
type MockServerExporter_RecordStatistics_Call struct {
	*mock.Call
}

// RecordStatistics is a helper method to define mock.On call
//   - stats *scaleset.RunnerScaleSetStatistic
func (_e *MockServerExporter_Expecter) RecordStatistics(stats interface{}) *MockServerExporter_RecordStatistics_Call {
	return &MockServerExporter_RecordStatistics_Call{Call: _e.mock.On("RecordStatistics", stats)}
}

func (_c *MockServerExporter_RecordStatistics_Call) Run(run func(stats *scaleset.RunnerScaleSetStatistic)) *MockServerExporter_RecordStatistics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *scaleset.RunnerScaleSetStatistic
		if args[0] != nil {
			arg0 = args[0].(*scaleset.RunnerScaleSetStatistic)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServerExporter_RecordStatistics_Call) Return() *MockServerExporter_RecordStatistics_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerExporter_RecordStatistics_Call) RunAndReturn(run func(stats *scaleset.RunnerScaleSetStatistic)) *MockServerExporter_RecordStatistics_Call {
	_c.Run(run)
	return _c
}

// SetAdvertisedMaxRunners provides a mock function for the type MockServerExporter
func (_mock *MockServerExporter) SetAdvertisedMaxRunners(value int) {
	_mock.Called(value)
	return
}

// MockServerExporter_SetAdvertisedMaxRunners_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAdvertisedMaxRunners'
type MockServerExporter_SetAdvertisedMaxRunners_Call struct {
	*mock.Call
}

// SetAdvertisedMaxRunners is a helper method to define mock.On call
//   - value int
func (_e *MockServerExporter_Expecter) SetAdvertisedMaxRunners(value interface{}) *MockServerExporter_SetAdvertisedMaxRunners_Call {
	return &MockServerExporter_SetAdvertisedMaxRunners_Call{Call: _e.mock.On("SetAdvertisedMaxRunners", value)}
}

func (_c *MockServerExporter_SetAdvertisedMaxRunners_Call) Run(run func(value int)) *MockServerExporter_SetAdvertisedMaxRunners_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServerExporter_SetAdvertisedMaxRunners_Call) Return() *MockServerExporter_SetAdvertisedMaxRunners_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerExporter_SetAdvertisedMaxRunners_Call) RunAndReturn(run func(value int)) *MockServerExporter_SetAdvertisedMaxRunners_Call {
	_c.Run(run)
	return _c
}

// SetDesiredPairs provides a mock function for the type MockServerExporter
func (_mock *MockServerExporter) SetDesiredPairs(value int) {
	_mock.Called(value)
	return
}

// MockServerExporter_SetDesiredPairs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDesiredPairs'
type MockServerExporter_SetDesiredPairs_Call struct {
	*mock.Call
}

// SetDesiredPairs is a helper method to define mock.On call
//   - value int
func (_e *MockServerExporter_Expecter) SetDesiredPairs(value interface{}) *MockServerExporter_SetDesiredPairs_Call {
	return &MockServerExporter_SetDesiredPairs_Call{Call: _e.mock.On("SetDesiredPairs", value)}
}

func (_c *MockServerExporter_SetDesiredPairs_Call) Run(run func(value int)) *MockServerExporter_SetDesiredPairs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServerExporter_SetDesiredPairs_Call) Return() *MockServerExporter_SetDesiredPairs_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerExporter_SetDesiredPairs_Call) RunAndReturn(run func(value int)) *MockServerExporter_SetDesiredPairs_Call {
	_c.Run(run)
	return _c
}

// SetHUDEnabled provides a mock function for the type MockServerExporter
func (_mock *MockServerExporter) SetHUDEnabled(enabled bool) {
	_mock.Called(enabled)
	return
}

// MockServerExporter_SetHUDEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHUDEnabled'
type MockServerExporter_SetHUDEnabled_Call struct {
	*mock.Call
}

// SetHUDEnabled is a helper method to define mock.On call
//   - enabled bool
func (_e *MockServerExporter_Expecter) SetHUDEnabled(enabled interface{}) *MockServerExporter_SetHUDEnabled_Call {
	return &MockServerExporter_SetHUDEnabled_Call{Call: _e.mock.On("SetHUDEnabled", enabled)}
}

func (_c *MockServerExporter_SetHUDEnabled_Call) Run(run func(enabled bool)) *MockServerExporter_SetHUDEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServerExporter_SetHUDEnabled_Call) Return() *MockServerExporter_SetHUDEnabled_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerExporter_SetHUDEnabled_Call) RunAndReturn(run func(enabled bool)) *MockServerExporter_SetHUDEnabled_Call {
	_c.Run(run)
	return _c
}

// SetPairs provides a mock function for the type MockServerExporter
func (_mock *MockServerExporter) SetPairs(value int) {
	_mock.Called(value)
	return
}

// MockServerExporter_SetPairs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPairs'
type MockServerExporter_SetPairs_Call struct {
	*mock.Call
}

// SetPairs is a helper method to define mock.On call
//   - value int
func (_e *MockServerExporter_Expecter) SetPairs(value interface{}) *MockServerExporter_SetPairs_Call {
	return &MockServerExporter_SetPairs_Call{Call: _e.mock.On("SetPairs", value)}
}

func (_c *MockServerExporter_SetPairs_Call) Run(run func(value int)) *MockServerExporter_SetPairs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServerExporter_SetPairs_Call) Return() *MockServerExporter_SetPairs_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerExporter_SetPairs_Call) RunAndReturn(run func(value int)) *MockServerExporter_SetPairs_Call {
	_c.Run(run)
	return _c
}

// SetPlaceholderPods provides a mock function for the type MockServerExporter
func (_mock *MockServerExporter) SetPlaceholderPods(role string, phase string, value int) {
	_mock.Called(role, phase, value)
	return
}

// MockServerExporter_SetPlaceholderPods_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPlaceholderPods'
type MockServerExporter_SetPlaceholderPods_Call struct {
	*mock.Call
}

// SetPlaceholderPods is a helper method to define mock.On call
//   - role string
//   - phase string
//   - value int
func (_e *MockServerExporter_Expecter) SetPlaceholderPods(role interface{}, phase interface{}, value interface{}) *MockServerExporter_SetPlaceholderPods_Call {
	return &MockServerExporter_SetPlaceholderPods_Call{Call: _e.mock.On("SetPlaceholderPods", role, phase, value)}
}

func (_c *MockServerExporter_SetPlaceholderPods_Call) Run(run func(role string, phase string, value int)) *MockServerExporter_SetPlaceholderPods_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockServerExporter_SetPlaceholderPods_Call) Return() *MockServerExporter_SetPlaceholderPods_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerExporter_SetPlaceholderPods_Call) RunAndReturn(run func(role string, phase string, value int)) *MockServerExporter_SetPlaceholderPods_Call {
	_c.Run(run)
	return _c
}

// SetProactiveCapacity provides a mock function for the type MockServerExporter
func (_mock *MockServerExporter) SetProactiveCapacity(value int) {
	_mock.Called(value)
	return
}

// MockServerExporter_SetProactiveCapacity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetProactiveCapacity'
type MockServerExporter_SetProactiveCapacity_Call struct {
	*mock.Call
}

// SetProactiveCapacity is a helper method to define mock.On call
//   - value int
func (_e *MockServerExporter_Expecter) SetProactiveCapacity(value interface{}) *MockServerExporter_SetProactiveCapacity_Call {
	return &MockServerExporter_SetProactiveCapacity_Call{Call: _e.mock.On("SetProactiveCapacity", value)}
}

func (_c *MockServerExporter_SetProactiveCapacity_Call) Run(run func(value int)) *MockServerExporter_SetProactiveCapacity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServerExporter_SetProactiveCapacity_Call) Return() *MockServerExporter_SetProactiveCapacity_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerExporter_SetProactiveCapacity_Call) RunAndReturn(run func(value int)) *MockServerExporter_SetProactiveCapacity_Call {
	_c.Run(run)
	return _c
}

// SetQueuedJobs provides a mock function for the type MockServerExporter
func (_mock *MockServerExporter) SetQueuedJobs(value int) {
	_mock.Called(value)
	return
}

// MockServerExporter_SetQueuedJobs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetQueuedJobs'
type MockServerExporter_SetQueuedJobs_Call struct {
	*mock.Call
}

// SetQueuedJobs is a helper method to define mock.On call
//   - value int
func (_e *MockServerExporter_Expecter) SetQueuedJobs(value interface{}) *MockServerExporter_SetQueuedJobs_Call {
	return &MockServerExporter_SetQueuedJobs_Call{Call: _e.mock.On("SetQueuedJobs", value)}
}

func (_c *MockServerExporter_SetQueuedJobs_Call) Run(run func(value int)) *MockServerExporter_SetQueuedJobs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServerExporter_SetQueuedJobs_Call) Return() *MockServerExporter_SetQueuedJobs_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerExporter_SetQueuedJobs_Call) RunAndReturn(run func(value int)) *MockServerExporter_SetQueuedJobs_Call {
	_c.Run(run)
	return _c
}

// SetReconcileLastSuccess provides a mock function for the type MockServerExporter
func (_mock *MockServerExporter) SetReconcileLastSuccess(phase string, t time.Time) {
	_mock.Called(phase, t)
	return
}

// MockServerExporter_SetReconcileLastSuccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetReconcileLastSuccess'
type MockServerExporter_SetReconcileLastSuccess_Call struct {
	*mock.Call
}

// SetReconcileLastSuccess is a helper method to define mock.On call
//   - phase string
//   - t time.Time
func (_e *MockServerExporter_Expecter) SetReconcileLastSuccess(phase interface{}, t interface{}) *MockServerExporter_SetReconcileLastSuccess_Call {
	return &MockServerExporter_SetReconcileLastSuccess_Call{Call: _e.mock.On("SetReconcileLastSuccess", phase, t)}
}

func (_c *MockServerExporter_SetReconcileLastSuccess_Call) Run(run func(phase string, t time.Time)) *MockServerExporter_SetReconcileLastSuccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServerExporter_SetReconcileLastSuccess_Call) Return() *MockServerExporter_SetReconcileLastSuccess_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerExporter_SetReconcileLastSuccess_Call) RunAndReturn(run func(phase string, t time.Time)) *MockServerExporter_SetReconcileLastSuccess_Call {
	_c.Run(run)
	return _c
}

// SetRunningPairs provides a mock function for the type MockServerExporter
func (_mock *MockServerExporter) SetRunningPairs(value int) {
	_mock.Called(value)
	return
}

// MockServerExporter_SetRunningPairs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetRunningPairs'
type MockServerExporter_SetRunningPairs_Call struct {
	*mock.Call
}

// SetRunningPairs is a helper method to define mock.On call
//   - value int
func (_e *MockServerExporter_Expecter) SetRunningPairs(value interface{}) *MockServerExporter_SetRunningPairs_Call {
	return &MockServerExporter_SetRunningPairs_Call{Call: _e.mock.On("SetRunningPairs", value)}
}

func (_c *MockServerExporter_SetRunningPairs_Call) Run(run func(value int)) *MockServerExporter_SetRunningPairs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServerExporter_SetRunningPairs_Call) Return() *MockServerExporter_SetRunningPairs_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerExporter_SetRunningPairs_Call) RunAndReturn(run func(value int)) *MockServerExporter_SetRunningPairs_Call {
	_c.Run(run)
	return _c
}
