// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package metrics

import (
	"context"

	"github.com/actions/scaleset"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRecorder creates a new instance of MockRecorder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRecorder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRecorder {
	mock := &MockRecorder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRecorder is an autogenerated mock type for the Recorder type
type MockRecorder struct {
	mock.Mock
}

type MockRecorder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRecorder) EXPECT() *MockRecorder_Expecter {
	return &MockRecorder_Expecter{mock: &_m.Mock}
}

// RecordDesiredRunners provides a mock function for the type MockRecorder
func (_mock *MockRecorder) RecordDesiredRunners(count int) {
	_mock.Called(count)
	return
}

// MockRecorder_RecordDesiredRunners_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordDesiredRunners'
type MockRecorder_RecordDesiredRunners_Call struct {
	*mock.Call
}

// RecordDesiredRunners is a helper method to define mock.On call
//   - count int
func (_e *MockRecorder_Expecter) RecordDesiredRunners(count interface{}) *MockRecorder_RecordDesiredRunners_Call {
	return &MockRecorder_RecordDesiredRunners_Call{Call: _e.mock.On("RecordDesiredRunners", count)}
}

func (_c *MockRecorder_RecordDesiredRunners_Call) Run(run func(count int)) *MockRecorder_RecordDesiredRunners_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRecorder_RecordDesiredRunners_Call) Return() *MockRecorder_RecordDesiredRunners_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRecorder_RecordDesiredRunners_Call) RunAndReturn(run func(count int)) *MockRecorder_RecordDesiredRunners_Call {
	_c.Run(run)
	return _c
}

// RecordJobCompleted provides a mock function for the type MockRecorder
func (_mock *MockRecorder) RecordJobCompleted(msg *scaleset.JobCompleted) {
	_mock.Called(msg)
	return
}

// MockRecorder_RecordJobCompleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordJobCompleted'
type MockRecorder_RecordJobCompleted_Call struct {
	*mock.Call
}

// RecordJobCompleted is a helper method to define mock.On call
//   - msg *scaleset.JobCompleted
func (_e *MockRecorder_Expecter) RecordJobCompleted(msg interface{}) *MockRecorder_RecordJobCompleted_Call {
	return &MockRecorder_RecordJobCompleted_Call{Call: _e.mock.On("RecordJobCompleted", msg)}
}

func (_c *MockRecorder_RecordJobCompleted_Call) Run(run func(msg *scaleset.JobCompleted)) *MockRecorder_RecordJobCompleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *scaleset.JobCompleted
		if args[0] != nil {
			arg0 = args[0].(*scaleset.JobCompleted)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRecorder_RecordJobCompleted_Call) Return() *MockRecorder_RecordJobCompleted_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRecorder_RecordJobCompleted_Call) RunAndReturn(run func(msg *scaleset.JobCompleted)) *MockRecorder_RecordJobCompleted_Call {
	_c.Run(run)
	return _c
}

// RecordJobStarted provides a mock function for the type MockRecorder
func (_mock *MockRecorder) RecordJobStarted(msg *scaleset.JobStarted) {
	_mock.Called(msg)
	return
}

// MockRecorder_RecordJobStarted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordJobStarted'
type MockRecorder_RecordJobStarted_Call struct {
	*mock.Call
}

// RecordJobStarted is a helper method to define mock.On call
//   - msg *scaleset.JobStarted
func (_e *MockRecorder_Expecter) RecordJobStarted(msg interface{}) *MockRecorder_RecordJobStarted_Call {
	return &MockRecorder_RecordJobStarted_Call{Call: _e.mock.On("RecordJobStarted", msg)}
}

func (_c *MockRecorder_RecordJobStarted_Call) Run(run func(msg *scaleset.JobStarted)) *MockRecorder_RecordJobStarted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *scaleset.JobStarted
		if args[0] != nil {
			arg0 = args[0].(*scaleset.JobStarted)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRecorder_RecordJobStarted_Call) Return() *MockRecorder_RecordJobStarted_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRecorder_RecordJobStarted_Call) RunAndReturn(run func(msg *scaleset.JobStarted)) *MockRecorder_RecordJobStarted_Call {
	_c.Run(run)
	return _c
}

// RecordStatic provides a mock function for the type MockRecorder
func (_mock *MockRecorder) RecordStatic(min int, max int) {
	_mock.Called(min, max)
	return
}

// MockRecorder_RecordStatic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordStatic'
type MockRecorder_RecordStatic_Call struct {
	*mock.Call
}

// RecordStatic is a helper method to define mock.On call
//   - min int
//   - max int
func (_e *MockRecorder_Expecter) RecordStatic(min interface{}, max interface{}) *MockRecorder_RecordStatic_Call {
	return &MockRecorder_RecordStatic_Call{Call: _e.mock.On("RecordStatic", min, max)}
}

func (_c *MockRecorder_RecordStatic_Call) Run(run func(min int, max int)) *MockRecorder_RecordStatic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRecorder_RecordStatic_Call) Return() *MockRecorder_RecordStatic_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRecorder_RecordStatic_Call) RunAndReturn(run func(min int, max int)) *MockRecorder_RecordStatic_Call {
	_c.Run(run)
	return _c
}

// RecordStatistics provides a mock function for the type MockRecorder
func (_mock *MockRecorder) RecordStatistics(stats *scaleset.RunnerScaleSetStatistic) {
	_mock.Called(stats)
	return
}

// MockRecorder_RecordStatistics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordStatistics'
type MockRecorder_RecordStatistics_Call struct {
	*mock.Call
}

// RecordStatistics is a helper method to define mock.On call
//   - stats *scaleset.RunnerScaleSetStatistic
func (_e *MockRecorder_Expecter) RecordStatistics(stats interface{}) *MockRecorder_RecordStatistics_Call {
	return &MockRecorder_RecordStatistics_Call{Call: _e.mock.On("RecordStatistics", stats)}
}

func (_c *MockRecorder_RecordStatistics_Call) Run(run func(stats *scaleset.RunnerScaleSetStatistic)) *MockRecorder_RecordStatistics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *scaleset.RunnerScaleSetStatistic
		if args[0] != nil {
			arg0 = args[0].(*scaleset.RunnerScaleSetStatistic)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRecorder_RecordStatistics_Call) Return() *MockRecorder_RecordStatistics_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRecorder_RecordStatistics_Call) RunAndReturn(run func(stats *scaleset.RunnerScaleSetStatistic)) *MockRecorder_RecordStatistics_Call {
	_c.Run(run)
	return _c
}

// NewMockServerExporter creates a new instance of MockServerExporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServerExporter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServerExporter {
	mock := &MockServerExporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServerExporter is an autogenerated mock type for the ServerExporter type
type MockServerExporter struct {
	mock.Mock
}

type MockServerExporter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServerExporter) EXPECT() *MockServerExporter_Expecter {
	return &MockServerExporter_Expecter{mock: &_m.Mock}
}

// ListenAndServe provides a mock function for the type MockServerExporter
func (_mock *MockServerExporter) ListenAndServe(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListenAndServe")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServerExporter_ListenAndServe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListenAndServe'
type MockServerExporter_ListenAndServe_Call struct {
	*mock.Call
}

// ListenAndServe is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockServerExporter_Expecter) ListenAndServe(ctx interface{}) *MockServerExporter_ListenAndServe_Call {
	return &MockServerExporter_ListenAndServe_Call{Call: _e.mock.On("ListenAndServe", ctx)}
}

func (_c *MockServerExporter_ListenAndServe_Call) Run(run func(ctx context.Context)) *MockServerExporter_ListenAndServe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServerExporter_ListenAndServe_Call) Return(err error) *MockServerExporter_ListenAndServe_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServerExporter_ListenAndServe_Call) RunAndReturn(run func(ctx context.Context) error) *MockServerExporter_ListenAndServe_Call {
	_c.Call.Return(run)
	return _c
}

// RecordDesiredRunners provides a mock function for the type MockServerExporter
func (_mock *MockServerExporter) RecordDesiredRunners(count int) {
	_mock.Called(count)
	return
}

// MockServerExporter_RecordDesiredRunners_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordDesiredRunners'
type MockServerExporter_RecordDesiredRunners_Call struct {
	*mock.Call
}

// RecordDesiredRunners is a helper method to define mock.On call
//   - count int
func (_e *MockServerExporter_Expecter) RecordDesiredRunners(count interface{}) *MockServerExporter_RecordDesiredRunners_Call {
	return &MockServerExporter_RecordDesiredRunners_Call{Call: _e.mock.On("RecordDesiredRunners", count)}
}

func (_c *MockServerExporter_RecordDesiredRunners_Call) Run(run func(count int)) *MockServerExporter_RecordDesiredRunners_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServerExporter_RecordDesiredRunners_Call) Return() *MockServerExporter_RecordDesiredRunners_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerExporter_RecordDesiredRunners_Call) RunAndReturn(run func(count int)) *MockServerExporter_RecordDesiredRunners_Call {
	_c.Run(run)
	return _c
}

// RecordJobCompleted provides a mock function for the type MockServerExporter
func (_mock *MockServerExporter) RecordJobCompleted(msg *scaleset.JobCompleted) {
	_mock.Called(msg)
	return
}

// MockServerExporter_RecordJobCompleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordJobCompleted'
type MockServerExporter_RecordJobCompleted_Call struct {
	*mock.Call
}

// RecordJobCompleted is a helper method to define mock.On call
//   - msg *scaleset.JobCompleted
func (_e *MockServerExporter_Expecter) RecordJobCompleted(msg interface{}) *MockServerExporter_RecordJobCompleted_Call {
	return &MockServerExporter_RecordJobCompleted_Call{Call: _e.mock.On("RecordJobCompleted", msg)}
}

func (_c *MockServerExporter_RecordJobCompleted_Call) Run(run func(msg *scaleset.JobCompleted)) *MockServerExporter_RecordJobCompleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *scaleset.JobCompleted
		if args[0] != nil {
			arg0 = args[0].(*scaleset.JobCompleted)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServerExporter_RecordJobCompleted_Call) Return() *MockServerExporter_RecordJobCompleted_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerExporter_RecordJobCompleted_Call) RunAndReturn(run func(msg *scaleset.JobCompleted)) *MockServerExporter_RecordJobCompleted_Call {
	_c.Run(run)
	return _c
}

// RecordJobStarted provides a mock function for the type MockServerExporter
func (_mock *MockServerExporter) RecordJobStarted(msg *scaleset.JobStarted) {
	_mock.Called(msg)
	return
}

// MockServerExporter_RecordJobStarted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordJobStarted'
type MockServerExporter_RecordJobStarted_Call struct {
	*mock.Call
}

// RecordJobStarted is a helper method to define mock.On call
//   - msg *scaleset.JobStarted
func (_e *MockServerExporter_Expecter) RecordJobStarted(msg interface{}) *MockServerExporter_RecordJobStarted_Call {
	return &MockServerExporter_RecordJobStarted_Call{Call: _e.mock.On("RecordJobStarted", msg)}
}

func (_c *MockServerExporter_RecordJobStarted_Call) Run(run func(msg *scaleset.JobStarted)) *MockServerExporter_RecordJobStarted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *scaleset.JobStarted
		if args[0] != nil {
			arg0 = args[0].(*scaleset.JobStarted)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServerExporter_RecordJobStarted_Call) Return() *MockServerExporter_RecordJobStarted_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerExporter_RecordJobStarted_Call) RunAndReturn(run func(msg *scaleset.JobStarted)) *MockServerExporter_RecordJobStarted_Call {
	_c.Run(run)
	return _c
}

// RecordStatic provides a mock function for the type MockServerExporter
func (_mock *MockServerExporter) RecordStatic(min int, max int) {
	_mock.Called(min, max)
	return
}

// MockServerExporter_RecordStatic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordStatic'
type MockServerExporter_RecordStatic_Call struct {
	*mock.Call
}

// RecordStatic is a helper method to define mock.On call
//   - min int
//   - max int
func (_e *MockServerExporter_Expecter) RecordStatic(min interface{}, max interface{}) *MockServerExporter_RecordStatic_Call {
	return &MockServerExporter_RecordStatic_Call{Call: _e.mock.On("RecordStatic", min, max)}
}

func (_c *MockServerExporter_RecordStatic_Call) Run(run func(min int, max int)) *MockServerExporter_RecordStatic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServerExporter_RecordStatic_Call) Return() *MockServerExporter_RecordStatic_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerExporter_RecordStatic_Call) RunAndReturn(run func(min int, max int)) *MockServerExporter_RecordStatic_Call {
	_c.Run(run)
	return _c
}

// RecordStatistics provides a mock function for the type MockServerExporter
func (_mock *MockServerExporter) RecordStatistics(stats *scaleset.RunnerScaleSetStatistic) {
	_mock.Called(stats)
	return
}

// MockServerExporter_RecordStatistics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordStatistics'
type MockServerExporter_RecordStatistics_Call struct {
	*mock.Call
}

// RecordStatistics is a helper method to define mock.On call
//   - stats *scaleset.RunnerScaleSetStatistic
func (_e *MockServerExporter_Expecter) RecordStatistics(stats interface{}) *MockServerExporter_RecordStatistics_Call {
	return &MockServerExporter_RecordStatistics_Call{Call: _e.mock.On("RecordStatistics", stats)}
}

func (_c *MockServerExporter_RecordStatistics_Call) Run(run func(stats *scaleset.RunnerScaleSetStatistic)) *MockServerExporter_RecordStatistics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *scaleset.RunnerScaleSetStatistic
		if args[0] != nil {
			arg0 = args[0].(*scaleset.RunnerScaleSetStatistic)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServerExporter_RecordStatistics_Call) Return() *MockServerExporter_RecordStatistics_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerExporter_RecordStatistics_Call) RunAndReturn(run func(stats *scaleset.RunnerScaleSetStatistic)) *MockServerExporter_RecordStatistics_Call {
	_c.Run(run)
	return _c
}
