# Health check patch for actions.github.com/v1alpha1 EphemeralRunner (New API)
# This patch adds health check for EphemeralRunner resources to ArgoCD
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  resource.customizations.health.actions.github.com_EphemeralRunner: |
    hs = {}
    if obj.status then
      local phase = obj.status.phase
      if phase == "Running" or phase == "Succeeded" or phase == "Finished" then
        if obj.status.jobRequestId then
          hs.status = "Healthy"
          hs.message = "EphemeralRunner is running job: " .. tostring(obj.status.jobRequestId)
        else
          hs.status = "Healthy"
          hs.message = "EphemeralRunner is running and ready for jobs"
        end
      elseif phase == "Pending" or phase == "PodCreated" then
        hs.status = "Progressing"
        hs.message = "EphemeralRunner is starting up"
      elseif phase == "Failed" then
        hs.status = "Degraded"
        hs.message = obj.status.message or "EphemeralRunner has failed"
      elseif phase == "Deleting" or phase == "Terminating" then
        hs.status = "Progressing"
        hs.message = "EphemeralRunner is cleaning up"
      else
        hs.status = "Progressing"
        hs.message = "EphemeralRunner status: " .. (phase or "(nil)")
      end

      if obj.status.runnerId then
        hs.message = hs.message .. " (ID: " .. tostring(obj.status.runnerId) .. ")"
      end
    else
      hs.status = "Progressing"
      hs.message = "Waiting for EphemeralRunner status"
    end
    return hs