apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  # Health check for actions.summerwind.dev/v1alpha1 Runner
  resource.customizations.health.actions.summerwind.dev_Runner: |
    hs = {}
    if obj.status ~= nil then
      local phase = obj.status.phase
      if obj.status.ready and phase == "Running" then
        hs.status = "Healthy"
        hs.message = "Runner is ready and running"
      elseif phase == "Pending" or phase == "Created" then
        hs.status = "Progressing"
        hs.message = "Runner is starting up"
      elseif phase == "Failed" then
        hs.status = "Degraded"
        hs.message = obj.status.message or "Runner has failed"
      else
        hs.status = "Progressing"
        hs.message = "Runner status: " .. (phase or "Unknown")
      end
    else
      hs.status = "Progressing"
      hs.message = "Waiting for runner status"
    end
    return hs
