{{- if .Values.controller.rbac.aggregateRoles.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "gha-controller.aggregate-view-role-name" . }}
  labels:
    {{- include "gha-controller.labels" . | nindent 4 }}
    rbac.authorization.k8s.io/aggregate-to-view: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
- apiGroups:
  - actions.github.com
  resources:
  - autoscalingrunnersets
  - autoscalingrunnersets/status
  - autoscalinglisteners
  - autoscalinglisteners/status
  - ephemeralrunnersets
  - ephemeralrunnersets/status
  - ephemeralrunners
  - ephemeralrunners/status
  verbs:
  - get
  - list
  - watch
{{- end }}
