name: (gha) Validate Helm Charts

on:
  pull_request:
    branches:
      - master
    paths:
      - "charts/**"
      - ".github/workflows/gha-validate-chart.yaml"
      - "!charts/actions-runner-controller/**"
      - "!**.md"
  push:
    paths:
      - "charts/**"
      - ".github/workflows/gha-validate-chart.yaml"
      - "!charts/actions-runner-controller/**"
      - "!**.md"
  workflow_dispatch:
env:
  KUBE_SCORE_VERSION: 1.16.1
  HELM_VERSION: v3.19.4

permissions:
  contents: read

concurrency:
  # This will make sure we only apply the concurrency limits on pull requests
  # but not pushes to master branch by making the concurrency group name unique
  # for pushes
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  validate-chart:
    name: Lint Chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4
        with:
          version: ${{ env.HELM_VERSION }}

      # python is a requirement for the chart-testing action below (supports yamllint among other tests)
      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Set up chart-testing
        uses: helm/chart-testing-action@6ec842c01de15ebb84c8627d2744a0c2f2755c9f

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          ct version
          changed=$(ct list-changed --config charts/.ci/ct-config-gha.yaml)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
          echo "changed_charts<<EOF" >> $GITHUB_OUTPUT
          echo "$changed" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Run chart-testing (lint)
        run: |
          ct lint --config charts/.ci/ct-config-gha.yaml

  test-chart:
    name: Test Chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4
        with:
          version: ${{ env.HELM_VERSION }}

      # python is a requirement for the chart-testing action below (supports yamllint among other tests)
      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Set up chart-testing
        uses: helm/chart-testing-action@6ec842c01de15ebb84c8627d2744a0c2f2755c9f

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          ct version
          changed=$(ct list-changed --config charts/.ci/ct-config-gha.yaml)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
          echo "changed_charts<<EOF" >> $GITHUB_OUTPUT
          echo "$changed" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Install helm-unittest
        run: |
          helm plugin install https://github.com/helm-unittest/helm-unittest.git

      - name: Run helm-unittest (gha-runner-scale-set-controller-experimental)
        run: |
          helm unittest ./charts/gha-runner-scale-set-controller-experimental/

      - name: Run helm-unittest (gha-runner-scale-set-experimental)
        run: |
          helm unittest ./charts/gha-runner-scale-set-experimental/

      - uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
          cache: false

      - name: Test gha-runner-scale-set
        run: go test ./charts/gha-runner-scale-set/...

      - name: Test gha-runner-scale-set-controller
        run: go test ./charts/gha-runner-scale-set-controller/...
